# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Link Rot
email: james@orbific.com
description: "Audio for orbific.com"
subtitle: "Stories and discussion and noises"
lang: en-us
author: James Burt
copyright: "&#xA9; 2021"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://audio.orbific.com" # the base hostname & protocol for your site
twitter_username: orbific
github_username:  orbific

permalink: /:year/:title.html

#Timezone
timezone: Australia/Sydney

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

plugins:
  - jekyll-analytic

jekyll_analytics:
  Plausible:
    domain: 'audio.orbific.com'   # The domain configured in plausible
    source: 'https://plausible.example.com/js/plausible.js' #s
